C4Context
title "WaveTap - C4 System Context"


System_Ext(aircraft, "Aircraft Mode-S", "Broadcast ADS-B frames on 1090 MHz")
System_Ext(future_voice, "VHF Broadcast (Planned)", "Aviation-band audio capture and playback")
System_Ext(future_broadcast, "FM/AM Broadcast (Planned)", "FM/AM demodulation and playback")

Person(user, "User", "Interacts with GUI or Web API")

System_Boundary(wavetap, "WaveTap Platform") {
    System_Ext(rtlsdr, "USB RTL-SDR", "Receives RF signals over the air")
    System(sdr_cap, "SDR Capture Service", "Captures and processes radio signals from RTL-SDR hardware")
    System(database_api, "WaveTap API", "Flask REST API endpoints for interface and web dashboards")
    System(arbiter, "Arbiter Service (Planned)", "Flask control for coordinating and configuring SDR modules")
    SystemDb(data_store, "Data Store", "SQLite database shared across services")
    System(gui, "Desktop Python GUI", "Optional local situational awareness client")
}


Rel(aircraft, rtlsdr, "Broadcast Mode-S")
Rel(future_voice, rtlsdr, "Broadcast VHF")
Rel(future_broadcast, rtlsdr, "Broadcast FM/AM")
Rel(rtlsdr, sdr_cap, "USB IQ sampled")

Rel(sdr_cap, data_store, "Writes secoded ADS-B data")
Rel(data_store, database_api, "Reads ADS-B data")

Rel(user, database_api, "Explores dashboards & APIs", "HTTPS/WebSocket")
Rel(user, gui, "Interacts with system through local GUI", "Python Tkinter")
Rel(gui, database_api, "Fetches summaries", "Rest API")
Rel(database_api, arbiter, "Manages SDR modules", "HTTPS/JSON")
Rel(arbiter, rtlsdr, "Coordinates SDR configuration")
