C4Context
title "WaveTap - System Context"

System_Boundary(b1, "WaveTap") {
    Boundary(b2, "Hardware") {
        System_Ext(sdr, "USB RTL-SDR", "Hardware for capturing RF signals")
    }
    System(ui_service, "UI Service", "Provides user interface for data visualization")
    SystemDb(data_storage, "Data Storage Service", "Stores decoded data for analysis")
    System(wavetap, "WaveTap SDR Platform", "Processes and decodes RF signals")
}

Boundary(b0, "Radio Frequencies") {
    System_Ext(fm_radio, "Other Radio", "Broadcasts RF Signals")
    System_Ext(adsb_transmitter, "ADS-B Transmitter", "Broadcasts Aircraft Data")
    System_Ext(vhf_radio, "VHF Radio", "Broadcasts ATC Comms")
}

Rel(fm_radio, sdr, "Broadcasts signals to", "down")
Rel(adsb_transmitter, sdr, "Broadcasts signals to", "down")
Rel(vhf_radio, sdr, "Broadcasts signals to", "down")
Rel(sdr, wavetap, "Captures signals for", "right")
Rel(wavetap, data_storage, "Stores decoded data in", "down")
Rel(data_storage, ui_service, "Provides data to", "right")
Rel(ui_service, wavetap, "Interacts with", "up", "HTTPS/WebSocket")

%%UpdateElementStyle(ui_service, $fontColor="red", $bgColor="grey", $borderColor="red")
%% UpdateRelStyle(ui_service, wavetap, $textColor="blue", $lineColor="blue", $offsetX="5")
%% UpdateRelStyle(sdr, wavetap, $textColor="blue", $lineColor="blue", $offsetY="-10")
%% UpdateRelStyle(data_storage, ui_service, $textColor="blue", $lineColor="blue", $offsetY="-40", $offsetX="-50")

%% UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")