C4Container
title "WaveTap - C4 Container View"


System_Boundary(wavetap, "WaveTap Stack") {
  Container(database_api, "WaveTap API", "Rest API & Web Interface")
  Container(gui, "Desktop Python GUI", "Optional")
  ContainerDb(data_store, "Data Store", "SQLite Database")
  Container(arbiter, "Arbiter Service (Planned)", "SDR Controller")
  Container(sdr_cap, "SDR Capture Service", "SDR Decoder / Recorder")
  System_Ext(rtlsdr, "USB RTL-SDR", "Captures RF energy")
}

System_Boundary("rf_spectrum", "RF Spectrum") {
  System_Ext(aircraft, "Aircraft Mode-S", "Broadcast ADS-B frames on 1090 MHz")
  System_Ext(future_voice, "VHF Broadcast (Planned)", " VHF band audio capture and playback")
  System_Ext(future_broadcast, "FM/AM Broadcast (Planned)", "FM/AM demodulation and playback")
}

System_Boundary(wavetap_future, "Future WaveTap Extensions (Planned)") {
  Container_Ext(vhf_service, "VHF Voice Service (Planned)", "", "Future aviation-band audio playback")
  Container_Ext(fm_service, "FM Broadcast Service (Planned)", "", "Future FM monitoring & playback")
  Container_Ext(am_service, "AM Broadcast Service (Planned)", "", "Future AM monitoring & playback")
}

Person(user, "User", "Uses dashboards and module console")


Rel(arbiter, rtlsdr, "Control over WebSocket")
Rel(database_api, arbiter, "Planned Control Path")

Rel(aircraft, rtlsdr, "Broadcast Mode-S")
Rel(future_voice, rtlsdr, "Broadcast VHF")
Rel(future_broadcast, rtlsdr, "Broadcast FM/AM")

Rel(rtlsdr, vhf_service, "Planned IQ Stream")
Rel(rtlsdr, fm_service, "Planned IQ Stream")
Rel(rtlsdr, am_service, "Planned IQ Stream")

Rel(rtlsdr, sdr_cap, "IQ Stream")
Rel(sdr_cap, data_store, "Decoded ADS-B Data (JSON)")

Rel(data_store, database_api, "Reads stored data")
Rel(database_api, gui, "Uses REST Endpoints")

Rel(user, database_api, "Web Interface")
Rel(user, gui, "Python Tkinter Interface")
